export const CHANGE_COMMON_NAV = "CHANGE_COMMON_NAV";

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_INIT = "AUTH_INIT";
export const AUTH_ERRORS = "AUTH_ERRORS";
export const AUTH_CLEAN = "AUTH_CLEAN";
export const AUTH_CURRENT = "AUTH_CURRENT";
export const AUTH_SAVE = "AUTH_SAVE";

export const GET_ALL_TAGS = "GET_ALL_TAGS";
export const INIT_ALL_TAGS = "INIT_ALL_TAGS";

export const GET_HOME_ARTICLE_LIST = "GET_HOME_ARTICLE_LIST";
export const INIT_HOME_ARTICLE_LIST = "INIT_HOME_ARTICLE_LIST";
export const INIT_HOME_PAGE = "INIT_HOME_PAGE";
export const CHANGE_HOME_TAB = "CHANGE_HOME_TAB";

export const GET_ARTICLE_DETAILS = "GET_ARTICLE_DETAILS";
export const INIT_ARTICLE_DETAILS = "INIT_ARTICLE_DETAILS";
export const ARTICLE_FOLLOW_USER = "ARTICLE_FOLLOW_USER";
export const ARTICLE_UNFOLLOW_USER = "ARTICLE_UNFOLLOW_USER";
export const INIT_ARTICLE_DETAILS_USER = "INIT_ARTICLE_DETAILS_USER";
export const ARTICLE_FAVORITE = "ARTICLE_FAVORITE";
export const ARTICLE_UNFAVORITE = "ARTICLE_UNFAVORITE";

export const GET_ARTICLE_COMMENTS = "GET_ARTICLE_COMMENTS";
export const INIT_ARTICLE_COMMENTS = "INIT_ARTICLE_COMMENTS";
export const CREATE_ARTICLE_COMMENTS = "CREATE_ARTICLE_COMMENTS";
export const ADD_ARTICLE_COMMENTS = "ADD_ARTICLE_COMMENTS";
export const DELETE_ARTICLE_COMMENTS = "DELETE_ARTICLE_COMMENTS";

export const GET_ARTICLE_DETAILS_NEW_POST = "GET_ARTICLE_DETAILS_NEW_POST";
export const INIT_ARTICLE_DETAILS_NEW_POST = "INIT_ARTICLE_DETAILS_NEW_POST";
export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const INIT_ARTICLE_ERRORS = "INIT_ARTICLE_ERRORS";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const INIT_USER_PROFILE = "INIT_USER_PROFILE";
export const GET_PROFILE_ARTICLE = "GET_PROFILE_ARTICLE";
export const GET_PROFILE_FAVORITED = "GET_PROFILE_FAVORITED";
export const INIT_PROFILE_ARTICLE = "INIT_PROFILE_ARTICLE";
export const INIT_PROFILE_PAGE = "INIT_PROFILE_PAGE";